packages:
  - examples/*
  - packages/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - canvas
  - cbor-extract
  - esbuild
  - sharp
  - tiny-secp256k1
  - unrs-resolver
  - utf-8-validate
  - vue-demi
